name: algolia_helper

packages:
  - helper
  - insights

scripts:
  analyze:
    exec: dart analyze .

  format: 
    exec: dart format .

  fix:
    exec: dart fix --apply
    description: Find and fix static analysis issues in all packages

  get:
    exec: dart pub get
    description: Run `dart pub get` in all packages.

  pana:
    exec: pana --no-warning --exit-code-threshold 0
    description: |
      Run pub points check for all packages

  lint:pub:
    run: |
      melos exec -c 5 --no-private "dart pub publish --dry-run"
    description: |
      Run `pub publish --dry-run` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  test:
    run: melos exec -c 1 --fail-fast -- "flutter test --coverage"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test

command:
  version:
    hooks:
      preCommit: ./sync_version.sh