name: algolia_helper

packages:
  - helper_dart
  - helper_flutter
  - insights_dart

scripts:
  analyze:
    exec: dart analyze .

  format: 
    exec: dart format .

  test:all:
    run: melos run test:dart --no-select && melos run test:flutter --no-select
    description: Run all Dart & Flutter tests in this project.

  test:dart:
    run: melos exec -c 1 --fail-fast -- "flutter test --coverage"
    description: Run Dart tests for a specific package in this project.
    packageFilters:
      flutter: false
      dirExists: test

  test:flutter:
    run: melos exec -c 1 --fail-fast -- "flutter test --coverage"
    description: Run Flutter tests for a specific package in this project.
    packageFilters:
      flutter: true
      dirExists: test