name: algolia_insights
description: Algolia Insights for Dart provides a simple and flexible way to track events such as clicks, conversions, and views on search results.
version: 1.0.0-pre
homepage: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/flutter/
repository: https://github.com/algolia/algoliasearch-helper-flutter/tree/main/insights

environment:
  sdk: ">=2.17.5 <4.0.0"
  flutter: '>=1.17.0'
dependencies:
  algolia_client_insights: ">=1.2.0 <2.0.0"
  collection: ">=1.17.0 <2.0.0"
  flutter:
    sdk: flutter
  hive: ">=2.0.0 <3.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.7.0 <2.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  rxdart: ">=0.27.0 <1.0.0"
  uuid: ">=3.0.0 <5.0.0"

dev_dependencies:
  build_runner: ">=2.4.0 <3.0.0"
  lints: ">=2.0.0 <3.0.0"
  mockito: ">=5.0.0 <6.0.0"
  test: ">=1.0.0 <2.0.0"
  test_api: ">=0.2.1 <0.6.0"
