// Mocks generated by Mockito 5.4.0 from annotations
// in algolia_helper/test/multi_searcher_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:algolia_helper/algolia_helper.dart' as _i4;
import 'package:algolia_helper/src/multi_searcher.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i2.SearchService {
  MockSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SearchResponse>> performSearch(
          List<_i4.SearchState>? requests) =>
      (super.noSuchMethod(
        Invocation.method(
          #performSearch,
          [requests],
        ),
        returnValue:
            _i3.Future<List<_i4.SearchResponse>>.value(<_i4.SearchResponse>[]),
      ) as _i3.Future<List<_i4.SearchResponse>>);
}
