// Mocks generated by Mockito 5.4.2 from annotations
// in algolia_helper/test/multi_searcher_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:algolia_helper/src/model/multi_search_response.dart' as _i4;
import 'package:algolia_helper/src/model/multi_search_state.dart' as _i5;
import 'package:algolia_helper/src/service/multi_search_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MultiSearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultiSearchService extends _i1.Mock
    implements _i2.MultiSearchService {
  MockMultiSearchService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.MultiSearchResponse>> search(
          List<_i5.MultiSearchState>? states) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [states],
        ),
        returnValue: _i3.Future<List<_i4.MultiSearchResponse>>.value(
            <_i4.MultiSearchResponse>[]),
      ) as _i3.Future<List<_i4.MultiSearchResponse>>);
}
