# Created with package:mono_repo v6.4.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.4.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; PKGS: helper_dart, insights_dart; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_dart-insights_dart;commands:format-analyze_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_dart-insights_dart
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: helper_dart_pub_upgrade
        name: helper_dart; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_dart
      - name: "helper_dart; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.helper_dart_pub_upgrade.conclusion == 'success'"
        working-directory: helper_dart
      - name: "helper_dart; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.helper_dart_pub_upgrade.conclusion == 'success'"
        working-directory: helper_dart
      - id: insights_dart_pub_upgrade
        name: insights_dart; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: insights_dart
      - name: "insights_dart; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.insights_dart_pub_upgrade.conclusion == 'success'"
        working-directory: insights_dart
      - name: "insights_dart; dart analyze --fatal-infos ."
        run: dart analyze --fatal-infos .
        if: "always() && steps.insights_dart_pub_upgrade.conclusion == 'success'"
        working-directory: insights_dart
  job_003:
    name: "analyze_and_format; PKG: helper_flutter; `dart format --output=none --set-exit-if-changed .`, `flutter analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_flutter;commands:format-analyze_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_flutter
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@9d48f4efd5460d7013af812069d08b23f37aed20
        with:
          channel: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: helper_flutter_pub_upgrade
        name: helper_flutter; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_flutter
      - name: "helper_flutter; dart format --output=none --set-exit-if-changed ."
        run: "dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.helper_flutter_pub_upgrade.conclusion == 'success'"
        working-directory: helper_flutter
      - name: "helper_flutter; flutter analyze --fatal-infos ."
        run: flutter analyze --fatal-infos .
        if: "always() && steps.helper_flutter_pub_upgrade.conclusion == 'success'"
        working-directory: helper_flutter
  job_004:
    name: "unit_test; PKG: helper_dart; `dart test -p chrome`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_dart;commands:test_1"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_dart
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: helper_dart_pub_upgrade
        name: helper_dart; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_dart
      - name: "helper_dart; dart test -p chrome"
        run: dart test -p chrome
        if: "always() && steps.helper_dart_pub_upgrade.conclusion == 'success'"
        working-directory: helper_dart
    needs:
      - job_001
      - job_002
      - job_003
  job_005:
    name: "unit_test; PKGS: helper_dart, insights_dart; `dart test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_dart-insights_dart;commands:test_0"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_dart-insights_dart
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: helper_dart_pub_upgrade
        name: helper_dart; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_dart
      - name: helper_dart; dart test
        run: dart test
        if: "always() && steps.helper_dart_pub_upgrade.conclusion == 'success'"
        working-directory: helper_dart
      - id: insights_dart_pub_upgrade
        name: insights_dart; dart pub upgrade
        run: dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: insights_dart
      - name: insights_dart; dart test
        run: dart test
        if: "always() && steps.insights_dart_pub_upgrade.conclusion == 'success'"
        working-directory: insights_dart
    needs:
      - job_001
      - job_002
      - job_003
  job_006:
    name: "unit_test; PKG: helper_flutter; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@fd5de65bc895cf536527842281bea11763fefd77
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_flutter;commands:test_2"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:helper_flutter
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@9d48f4efd5460d7013af812069d08b23f37aed20
        with:
          channel: stable
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - id: helper_flutter_pub_upgrade
        name: helper_flutter; flutter pub upgrade
        run: flutter pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_flutter
      - name: helper_flutter; flutter test
        run: flutter test
        if: "always() && steps.helper_flutter_pub_upgrade.conclusion == 'success'"
        working-directory: helper_flutter
    needs:
      - job_001
      - job_002
      - job_003
