# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.3.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "unit_test; PKG: helper_dart; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.17.5;packages:helper_dart;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.5;packages:helper_dart
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.5
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@2fb73e25c9488eb544b9b14b2ce00c4c2baf789e
        with:
          channel: "2.17.5"
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: helper_dart_pub_upgrade
        name: helper_dart; flutter pub pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_dart
        run: flutter pub pub upgrade
      - name: helper_dart; flutter test
        if: "always() && steps.helper_dart_pub_upgrade.conclusion == 'success'"
        working-directory: helper_dart
        run: flutter test
    needs:
      - job_001
  job_003:
    name: "unit_test; PKG: helper_flutter; `flutter test`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:2.17.5;packages:helper_flutter;commands:test"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.5;packages:helper_flutter
            os:ubuntu-latest;pub-cache-hosted;sdk:2.17.5
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: subosito/flutter-action@2fb73e25c9488eb544b9b14b2ce00c4c2baf789e
        with:
          channel: "2.17.5"
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: helper_flutter_pub_upgrade
        name: helper_flutter; flutter pub pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: helper_flutter
        run: flutter pub pub upgrade
      - name: helper_flutter; flutter test
        if: "always() && steps.helper_flutter_pub_upgrade.conclusion == 'success'"
        working-directory: helper_flutter
        run: flutter test
    needs:
      - job_001
