name: Deployment
on: 
  workflow_dispatch:
    inputs:
      releaseType:
        description: 'The type of semantic release'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      RELEASE_TYPE: ${{ inputs.releaseType }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Check out polyglot
        uses: actions/checkout@v2
        with:
          repository: algolia/polyglot
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Install polyglot
        run: |
          make install
          export PATH="$GOPATH/bin:$PATH"

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bump library version based on the tag
        uses: fwilhe2/bump-version@main
        id: bump
        with:
          component: ${{ inputs.releaseType }}

      - name: Update Dart Helper version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helper_dart/pubspec.yaml'
          propertyPath: 'version'
          value: ${{ steps.bump.outputs.newVersion }}
          commitChange: false

      - name: Update Dart Helper dependency for Flutter Helper 
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helper_flutter/pubspec.yaml'
          propertyPath: 'dependencies.algolia_helper'
          value: ^${{ steps.bump.outputs.newVersion }}
          commitChange: false

      - name: Update Dart Helper version 
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helper_flutter/pubspec.yaml'
          propertyPath: 'version'
          value: ${{ steps.bump.outputs.newVersion }}
          commitChange: false

      - name: Generate Dart Helper changelog
        working-directory: helper_dart
        run: |
          polyglot changelog ${{ steps.bump.outputs.newVersion }}

      - name: Generate Flutter Helper changelog
        working-directory: helper_flutter
        run: |
          polyglot changelog ${{ steps.bump.outputs.newVersion }}

      - name: Generate release changelog
        run: |
          polyglot changelog ${{ steps.bump.outputs.newVersion }}

      - name: Generate version source file
        working-directory: helper_dart
        run: |
          version_file="lib/src/lib_version.dart"
          > $version_file
          echo "// This is generated file. Don't modify it manually." >> $version_file
          echo "const libVersion = '${{ steps.bump.outputs.newVersion }}';" >> $version_file

      - name: Commit release changes
        uses: EndBug/add-and-commit@v9
        with:
          add: helper_flutter/pubspec.yaml helper_flutter/CHANGELOG.md helper_dart/pubspec.yaml helper_dart/CHANGELOG.md helper_dart/lib/src/lib_version.dart
          message: 'chore: prepare next release ${{ steps.bump.outputs.newVersion }}'
          new_branch: release-${{ steps.bump.outputs.newVersion }}
          tag: '${{ steps.bump.outputs.newVersion }}'

      - name: Release 
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: ${{ steps.bump.outputs.newVersion }}
          draft: true
          body_path: CHANGELOG.md
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        env:
          GITHUB_REPOSITORY: algolia/algoliasearch-helper-flutter

      - uses: dart-lang/setup-dart@v1.3

      - name: Activate pana
        run: dart pub global activate pana

      - name: Check and publish Dart helper
        working-directory: helper_dart
        run: |
          pana --no-warning
          dart pub publish --dry-run

      - uses: subosito/flutter-action@v2

      - name: Check and publish Flutter helper
        working-directory: helper_flutter
        run: |
          pana --no-warning
          flutter pub publish --dry-run

      





      
